#!/bin/bash

set -e

WHICH=ngdemo

rm -f $WHICH.bin

curl https://conservify.page5of4.com/distribution/okavango/$WHICH/latest/adafruit-samd-adafruit_feather_m0/$WHICH.bin -o $WHICH.bin

./bossac_osx  -i -d --port=$1 -U true -i -e -w -v $WHICH.bin -R
